### ISSUE TITLE
Clarification of FIPS 204 hint generation

### ISSUE THREAD

**Issue by GiacomoPope** [paulmillr/noble-post-quantum#6]
In your code you have the following comment:

https://github.com/paulmillr/noble-post-quantum/blob/fccc897cfac0a59e54d4478cfbd62e97662f2417/src/ml-dsa.ts#L167-L173

I got stuck on this too recently and ended up solving it with some help from friends. The TL;DR is that the hiny you're generating is using an optimisation in Dilithium spec section 5.1 and has a different form because of the way vectors are handled during signing.

See here for my fix: https://github.com/GiacomoPope/dilithium-py/issues/2
See here for my discussion: https://github.com/GiacomoPope/dilithium-py?tab=readme-ov-file#optimising-decomposition-and-making-hints

**Comment by paulmillr** [comment]
yeah, we should wait until final spec anywawy

**Comment by GiacomoPope** [comment]
Sure I was just making this issue because it was unclear to me if you were aware of why the make hint is different.

**Comment by GiacomoPope** [comment]
Oh sorry for closing it, I assumed that the info I gave was enough to clarify the comment and the choice of the algorithm would be a separate issue.
