### ISSUE TITLE
How to "unsign" or "decrypt" / "decode"

### ISSUE THREAD

**Issue by sspilleman** [paulmillr/noble-post-quantum#8]
Hi!

I'm trying to implement file encryption using one of your algorithms. (in this case ml_dsa65, the example on your website.)
```ts
import { ml_dsa44, ml_dsa65 as algo, ml_dsa87 } from "npm:@noble/post-quantum/ml-dsa";
const aliceKeys = algo.keygen(seed);
const msg = new TextEncoder().encode("thisisthemessage");
const sig = algo.sign(aliceKeys.secretKey, msg);
const isValid = algo.verify(aliceKeys.publicKey, msg, sig);
console.log("isValid", isValid);
```
Works perfectly prints `true`, so far so good.
I see the `sign` function as being "encrypt" / "encode" / "whatever", or so, right?

What i cannot find is the `unsign` function (or decrypt / decode/ whatever). Am I missing something? Or is this library not meant for that purpose? I would need something like:
```ts
if(isValid) {
    const original_msg: Uint8Array = algo.unsign(aliceKeys.secretKey, sig);
    const source = new TextDecoder().decode(original_msg);
    // source === "thisisthemessage"
}
```
Furthermore, I came to this choice for `ml-dsa` because _supposedly_ it supports streaming. It is not clear to me how I should implement that with `@noble/post-quantum/ml-dsa`. I can read a file in chunks, no prob, I then could sign each chunk and stream it across, also no prob. But how would I then implement the "receiving side"?
There I have the following questions;

- Again, Am I missing something? or or is this library not meant for that purpose? 
- The `sign` function adds quite a but of overhead to that small message in the example. For big files it is relatively better as I could work with 64k chunks, but still...

Thanks!

Sander

**Comment by paulmillr** [comment]
Hello.

> I see the sign function as being "encrypt" / "encode" / "whatever", or so, right?

Not really. Signatures only prove that you possess the key. If you need to encrypt something as well, hybrid encryption is required. Hybrid encryption encrypts stuff with one algorithm (AES or ChaCha), then signs it with another algorithm. Example of hybrid encryption are HPKE and ECIES.

For post-quantum, there is no good such standard for now. Some folks (Signal, iMessage) are using ML-KEM + ed25519 to do "diffie hellman" handshake and then create AES keys from it, but they don't use ML-DSA anywhere.

> ml-dsa because supposedly it supports streaming

We don't support streaming for now. Maybe in the future.

> The sign function adds quite a but of overhead

Correct - that's why basically nobody is using ML-DSA. It's too big / too slow.

**Comment by sspilleman** [comment]
Ok thanks! Really appreciate your quick elaborate response!

Maybe Its better to share my use-case and then ask for advice:

ATM I'm using usenet to create backups, because its mostly free (storage) apart for the fees for the usenet service which is also for free considering the amounts of data. Although I'm not backing up the most sensitive stuff, still I would like it to be "as safe as possible", hence I started looking @ post quantum algorithms.
So the requirement is "uploaded files, not able to decrypt post quantum"

Would you have an advice on how to proceed? I'm not an expert on encryption as you might have guessed from my initial question :-)
Would appreciate it a lot of you know of "some" solution. I'm using openpgp now, but afaik it doesn't support any PQC alogo's, but also there I might be missing something

Thanks!

**Comment by paulmillr** [comment]
Ciphers, such as AES-GCM, or ChaCha20Poly1305 - are post-quantum.

The data is usually encrypted by them. Which brings us to another question: how are cipher keys generated.

If you generate them from secure random (for example, /dev/urandom) and write down the keys somewhere, then you're ok. No need to use ECC, ML-DSA, ML-KEM, etc. Just one cipher is ok.

**Comment by sspilleman** [comment]
Thank you Paul again very much appreciated! I'll definitely look into those!
