### ISSUE TITLE
ML-DSA: missing context encoding step (only `internal` functions implemented?)

### ISSUE THREAD

**Issue by larabr** [paulmillr/noble-post-quantum#9]
It seems that the exposed `mldsa` sign and verify functions correspond to `ML-DSA.Sign_internal` and `Verify_internal` (i.e. Algo 7 and 8 in FIPS [204](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.204.pdf)), rather than Algo 2 and 3, which additionally encode a `context` string in input.

Is this intended? If so, I think this should be clarified in the README, as interoperability with other libs is affected.

**Comment by paulmillr** [comment]
f3580aff85a99c27bcd31b914c1f981aaba4a132 will expose context-based methods.

However, there are no test vectors for that.

Branch [wycheproof](https://github.com/paulmillr/noble-post-quantum/tree/wycheproof) incorporates vectors from https://github.com/C2SP/wycheproof/pull/112, but the upstream PR is not merged yet and unclear when it will be.

**Comment by paulmillr** [comment]
Exposed in 0.2.1

**Comment by larabr** [comment]
I think the SLH-DSA might have the same issue ? i.e. the lib is exposing Algorithm 19 instead of 22 (and same for the verification function) ? Spec: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.205.pdf .

**Comment by paulmillr** [comment]
@larabr fixed
